### ISSUE TITLE
Deployment script copies file incorrectly.

### ISSUE THREAD

**Issue by samyakbhuta** [FooBaroda/foobaroda.org#20]
When I do ```npm run deploy```, following command is executed and copies the entire ```build``` directory in ```gh-pages``` branch. Ideally, the content of the ```build``` directory needs to be copied directly into ```gh-pages``` branch, and not the directory.

Command Executed : ```npm run build && git-directory-deploy --directory build/ --branch gh-pages``` 

Related to #18.

**Comment by nayaabkhan** [comment]
@samyakbhuta Did you run the command actually? Because I don't see any commits in the gh-pages branch since I last pushed.

**Comment by samyakbhuta** [comment]
Ah, I tested it, again, and found out what lead me to believe it is a bug, in first place. My bad.

I used to ...
* ```npm run deploy```
* ```git checkout gh-pages```
* ```git status``` - This used to show me ```build``` directory, as there is no ```.gitignore``` in the ```gh-pages``` branch.
