### ISSUE TITLE
http-server command doesn't do anything.

### ISSUE THREAD

**Issue by pixeldetective** [FooBaroda/foobaroda.org#8]
After changing the directory to the build folder, trying the command ```http-server``` doesn't do anything. It says command not found.

**Comment by lakhansamani** [comment]
Do u have http-server node module installed ?

**Comment by pixeldetective** [comment]
No, I don't. The instructions don't any anything about needing it or how to install it.

**Comment by lakhansamani** [comment]
I am adding that package to package.json, so probably after pulling code from remote and executing npm install will do all work for u

**Comment by pixeldetective** [comment]
So do I need to do the whole thing again? Clone the repo and all?

**Comment by pixeldetective** [comment]
Readme file has been updated with instructions.
